name: 'CI'
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.16, 1.17, 1.18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@1.7.0
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
      - run: 'go vet ./...'
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: '2021.1.1'
          install-go: false
          cache-key: ${{ matrix.go-version }}
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.16, 1.17, 1.18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: 'go build ./...'
        